name: CycloneDX1 SBOM

on:
  push:
    branches:
      - druid-27.0.0_release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Generate CycloneDX SBOM
      run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom -DbomFormat=JSON

    - name: Upload SBOM
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: target/bom.json
