name: SBOM_Cyclonedx

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install CycloneDX
      run: |
        # Install CycloneDX here

    - name: Generate SBOM
      run: |
        cyclonedx-bom -s /d/BeSecure/Aditi8007/druid -o sbom.json --include-dependencies --spec-version 1.3 --format json

    - name: Publish SBOM as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: sbom.xml
