name: Generate SBOM

on:
  push:
    branches:
      - druid-27.0.0_release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install CycloneDX
      run: |
        sudo apt-get install -y python3-pip
        pip3 install cyclonedx-py==22.0.2+dfsg-1ubuntu0.4
    - name: Generate SBOM
      run: |
        cyclonedx-py -o sbom.json --include-dependencies --spec-version 1.3 --format json
    - name: Publish SBOM as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: sbom.json
