name: CycloneDX SBOM Report

on:
 push:
  branches: druid-27.0.0_release

jobs:
  cyclonedx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Generate SBOM report
      uses: cyclonedx/github-action@0.4.0
      with:
        input : './'
        output: 'bom.json'
        formate: 'json'
        
    - name: commit and push SBOM report
      run: |
       git config --local user.email "aditi.salokhe@wipro.com"
       git config --local user.name "Aditi8007"
       git add bom.json
       git commit -m "Add sbom report"
       git push
      
